/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

    int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{

    static int  result;

    printf("this function called\n");
    printf("parameters:"); 
    result = argp->a + argp->b;
    printf("returning: %d\n", result);
    return(&result);
}
