/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stat.h"


void
stats_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * search_1_arg;
	int  *result_2;
	char * zero_1_arg;
	int  *result_3;
	char * sum_1_arg;
	int  *result_4;
	char * median_1_arg;
	int  *result_5;
	char * average_1_arg;
	int  *result_6;
	char * stddev_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, STATS, STATSVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = search_1(&search_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = zero_1(&zero_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = sum_1(&sum_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = median_1(&median_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = average_1(&average_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = stddev_1(&stddev_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	stats_1 (host);
exit (0);
}
